### ISSUE TITLE
Failed to spawn command qtcreator

### ISSUE THREAD

**Issue by szhu** [gogoprog/atom-gdb#10]
> Failed to spawn command qtcreator. Make sure qtcreator is installed and on your PATH

Where can I get qtcreator?

**Comment by gogoprog** [comment]
This is the defaullt command which spawns qtcreator, it can be found here: http://www.qt.io/ide/

There is no support for VisualStudio on Windows at this moment...

**Comment by szhu** [comment]
Is there a brew or brew cask command I can use to install this? I tried a few qt ones and they didn't work.

**Comment by gogoprog** [comment]
It depends on your OS :
On Ubuntu ; sudo apt-get install qtcreator
On ArchLinux : pacman -S qtcreator
(etc)

What is yours?

**Comment by szhu** [comment]
[brew](http://brew.sh/) is Mac.

**Comment by szhu** [comment]
Is there a resolution to this? My question again:

> Is there a brew or brew cask command I can use to install this? I tried a few qt ones and they didn't work.

**Comment by gogoprog** [comment]
I closed it because it is not really related to the plugin itself.

To install qt-creator you should follow something like this : 
http://macappstore.org/qt-creator/

**Comment by szhu** [comment]
The problem is that `brew cask install qt-creator` doesn't fix install the `qtcreator` command-line tool. I'm opening this issue here because I don't know where I can find this tool.

Again, I tried all the `brew install qt*` and `brew cask install qt*` commands and none of them seemed to install a tool that makes this plugin happy.

**Comment by gogoprog** [comment]
I'll try and let you know

**Comment by gogoprog** [comment]
I found out that the command is :
/opt/homebrew-cask/Caskroom/qt-creator/3.5.0/Qt\ Creator.app/Contents/MacOS/Qt\ Creator

Because of the spaces I had to make a script in my PATH:
qtcreator:
/opt/homebrew-cask/Caskroom/qt-creator/3.5.0/Qt\ Creator.app/Contents/MacOS/Qt\ Creator $@

And now I can start debugging my apps, but the breakpoints are not functional yet...
I'll open a new more specific issue.

Thanks for feedbacks ;)

**Comment by szhu** [comment]
Thank you!
